[project]
name = "MoNet"
version = "0.1.0"
description = ""
authors = [
    {name = "hn3ng4n@163.com", email = "hn3ng4n@qq.com"},
]
dependencies = []
requires-python = ">=3.10"
readme = "README.md"
license = {text = "MIT"}

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"
